project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Ben Stockton's Stats Site"
  search: true
  cookie-consent: false
  twitter-card: true
  open-graph: true
  site-url: https://benjamin-stockton.github.io
  navbar:
    left:
      - about.qmd
      - blog.qmd
      - projects.qmd
      - publications.qmd
      # - text: CV
      #   href: "_site/2023_NSF_Resume_20230207.pdf"
    right:
      - icon: github
        href: https://github.com/benjamin-stockton
      - icon: linkedin
        href: https://linkedin.com/in/benjamin-stockton-329507160/
  page-footer:
    left: ""
  drafts:
    - posts/air-pollution-wind/air-pollution-wind.qmd
    - posts/longitudinal-models-baseball-careers/longitudinal-models-baseball-careers.qmd
    - posts/stan-pres-swosc/stan_pres.qmd
    - posts/bayesian-model-averaging/bma.qmd
  draft-mode: unlinked
  repo-url: https://github.com/benjamin-stockton/benjamin-stockton.github.io
  repo-actions: [edit, source, issue]

format:
  html:
    theme: 
      - sandstone
      - custom.scss
    css: styles.css
